version: '2'

services:
  composer:
    image: yiisoftware/yii2-php:7.4-apache
    environment:
      PHP_ENABLE_XDEBUG: 1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
      - ./.htaccess:/var/www/.htaccess

  php:
    image: php:7.4-apache
    ports:
      - 8008:80
    volumes:
      - ./public:/var/www/html
      - ./:/var/www

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: psr
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - 'db:/var/lib/mysql'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-psr
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8088:80

volumes:
  db: { }