version: '2'

services:
  composer:
    image: yiisoftware/yii2-php:7.4-apache
    environment:
      PHP_ENABLE_XDEBUG: 1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
